name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # pin@v4.0.0
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Initialize CodeQL
        uses: github/codeql-action/init@32dc499307d133bb5085bae78498c0ac2cf762d5 # pin@v2.2.5
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@32dc499307d133bb5085bae78498c0ac2cf762d5 # pin@2.2.5
        with:
          category: "/language:go"
